# Generated by Django 4.2.2 on 2023-10-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
