# Generated by Django 4.2.2 on 2023-10-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_register_table_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='my_cash',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
