# Generated by Django 4.2.2 on 2023-10-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_register_table_my_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='deposit_amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_table',
            name='transaction_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_table',
            name='withdraw_amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
