# Generated by Django 4.2.2 on 2023-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_register_table_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='transaction_date',
            new_name='deposit_transaction_date',
        ),
        migrations.AddField(
            model_name='register_table',
            name='withdraw_transaction_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
