# Generated by Django 4.2.2 on 2023-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_rename_transaction_date_register_table_deposit_transaction_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_statment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('deposit_amount', models.CharField(max_length=100)),
                ('withdraw_amount', models.CharField(max_length=100)),
                ('balance_amount', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=100)),
            ],
        ),
    ]
